### ISSUE TITLE
Upgrade Californium to 2.0.0

### ISSUE THREAD

**Issue by flo-02-mu** [openhab/openhab-core#1096]
[Californium](https://github.com/eclipse/californium/), the COAP protocol implementation used by openhab will release a new major version 2.0.0, soon. Since the 1.x branch will no longer be maintained, an update is highly recommended.

Affected bindings:

- Ikea Tradfri Binding (see also https://community.openhab.org/t/tradfri-ignoring-unmatchable-piggy-backed-response-from-x-x-x-x-5684/79469/31)
- Shelly Binding (see also https://community.openhab.org/t/shelly-binding/56862)

**Comment by cweitkamp** [comment]
To update the core feature we have to change the following lines:

https://github.com/openhab/openhab-core/blob/fa416be05771bdeefb7d660aea30a03767287060/features/karaf/openhab-tp/src/main/feature/feature.xml#L43-L48

This will affect all bindings using the feature. Thus we have to make sure the eventually necessary changes have to be in place too and should be merger directly after the core changes will have been merged.

**Comment by kaikreuzer** [comment]
Afair, Californium 2 isn't necessarily backward compatible (as it is a major version increase) and it also grew immensely in size. I thus do not see any immediate need to act, but rather think an update will be risky as it potentially negatively impacts the functionality of the current bindings.

On the long run I agree that if 1.x isn't any longer maintained, we will have to look into the upgrade, but this should be thoroughly analysed and tested.

**Comment by J-N-K** [comment]
I think that since only two bindings are affected, we should upgrade after we verified that they work with the new version. Especially if there are benefits with the new version.

**Comment by markus7017** [comment]
so chriscolden was able to solve an issue with the Tradfi binding (gateway frquently becoming offline) by upgrading to Californium 2.0.

The Shelly binding, which I'm working on requires a small PR, which will become part of 2.0-M17. Due to the fact that Shelly uses an non-standard request code there is no chance to get it running without a PR.

If we
- create a new feature californium2 and
- both bindings use that feature
we are fine. The old Tradfi binding uses californium 1.x whereas the new version of the binding uses V2 as well as the Shelly binding.

According Achim this bug should be fixed in 1.0.7, but obviously it's not. Due to the fact that it is already M18 I would expect the current build as kind of stable (final release is planned by end of the year).

Otherwise the Tardfi and Shelly bindings need to include "their" private Californium Builds, which doesn't make sense.

**Comment by chriscolden** [comment]
So for me the update to californium 2.0 means the logs no longer get spammed and the gateway seems more responsive when it works.

This does not solve the gateway going offline for me, that still happens, however when it does, the gateway no longer becomes unresponsive. Google home and tradfri apps still work just fine, only openhab has an issue.

Therefore I think its well worth the upgrade, although more work needs to happen with the tradfri binding to get it stable.

**Comment by markus7017** [comment]
any progress on the Calfornium 2.0 feature bundle for OH 2.5?

Ich asked the project when M19 becomes available and when the final Californium 2.0 release.

@cweitkamp Nevertheless we should continue on building the OH feature.

**Comment by kaikreuzer** [comment]
If both Tradfri and Shelly binding benefit from the upgrade, I am absolutely fine to go that way. I'd also claim that there is no need to keep the old feature, so upgrading it as @cweitkamp [suggested](https://github.com/openhab/openhab-core/issues/1096#issuecomment-538682382) should be fine.

**Comment by markus7017** [comment]
yes, that's my understanding
- Tradfi works at least way more stable with Californium 2.0-M17
- 2.0-M18 brings the PR for the Shelly binding - a mini change, but essential

So from my point of view we should build the feature based on 2.0-M18, whoch could be updated to the latest milestone build or even 2.0 final while releasing OH 2.5 final.

AFAIK those are the only 2 bindings based on Californium so from my point of view we can drop the 1.x feature bundle. For 2.4 I'll add instructions to the README how to add the 2 libs required by the Shelly binding so we have a solutions for both OH releases.

**Comment by markus7017** [comment]
@kaikreuzer  As you saw I started the PR for the Shelly Bindung. I need some final testing, then it's ready for review. It would make sense to have the openhab-transport-coap feature updated to Californium 2.0-M18 by then. Is anyone working on that?

**Comment by kaikreuzer** [comment]
I don't know, at least not me. Feel free to create a PR the way @cweitkamp suggested in https://github.com/openhab/openhab-core/issues/1096#issuecomment-538682382.

**Comment by cweitkamp** [comment]
@markus7017 I prepared https://github.com/openhab/openhab-core/pull/1201 for the Californium update.

**Comment by markus7017** [comment]
@flo-02-mu could you help with the PR and Tradfi bindnig update/testing
