### ISSUE TITLE
Access refused to https://openhab.org/schemas/binding-1.0.0.xsd and others

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-core#1239]
Since few days, my binding build is showing these errors:
```
[INFO] --- sat-plugin:0.8.0:checkstyle (sat-all) @ org.openhab.binding.snips ---
[INFO] Adding dependency to checkstyle:0.8.0
[INFO] Adding dependency to checkstyle:8.12
[ERROR] Unable to get XSD file https://openhab.org/schemas/binding-1.0.0.xsd : Unable to get https://openhab.org/schemas/binding-1.0.0.xsd
java.io.IOException: Unable to get https://openhab.org/schemas/binding-1.0.0.xsd
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:73)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.getXSD(EshInfXmlValidationCheck.java:233)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.beginProcessing(EshInfXmlValidationCheck.java:124)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:210)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
        at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
        at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:94)
        at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck(AbstractChecker.java:110)
        at org.openhab.tools.analysis.tools.CheckstyleChecker.execute(CheckstyleChecker.java:131)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://openhab.org/schemas/binding-1.0.0.xsd
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.openhab.tools.analysis.utils.CachingHttpClient.getContent(CachingHttpClient.java:80)
        at org.openhab.tools.analysis.utils.CachingHttpClient.lambda$get$0(CachingHttpClient.java:70)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870)
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:70)
        ... 34 more
[ERROR] Unable to get XSD file https://openhab.org/schemas/thing-description-1.0.0.xsd : Unable to get https://openhab.org/schemas/thing-description-1.0.0.xsd
java.io.IOException: Unable to get https://openhab.org/schemas/thing-description-1.0.0.xsd
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:73)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.getXSD(EshInfXmlValidationCheck.java:233)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.beginProcessing(EshInfXmlValidationCheck.java:125)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:210)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
        at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
        at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:94)
        at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck(AbstractChecker.java:110)
        at org.openhab.tools.analysis.tools.CheckstyleChecker.execute(CheckstyleChecker.java:131)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://openhab.org/schemas/thing-description-1.0.0.xsd
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.openhab.tools.analysis.utils.CachingHttpClient.getContent(CachingHttpClient.java:80)
        at org.openhab.tools.analysis.utils.CachingHttpClient.lambda$get$0(CachingHttpClient.java:70)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870)
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:70)
        ... 34 more
[ERROR] Unable to get XSD file https://openhab.org/schemas/config-description-1.0.0.xsd : Unable to get https://openhab.org/schemas/config-description-1.0.0.xsd
java.io.IOException: Unable to get https://openhab.org/schemas/config-description-1.0.0.xsd
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:73)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.getXSD(EshInfXmlValidationCheck.java:233)
        at org.openhab.tools.analysis.checkstyle.EshInfXmlValidationCheck.beginProcessing(EshInfXmlValidationCheck.java:126)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:210)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
        at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
        at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:143)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:94)
        at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck(AbstractChecker.java:110)
        at org.openhab.tools.analysis.tools.CheckstyleChecker.execute(CheckstyleChecker.java:131)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://openhab.org/schemas/config-description-1.0.0.xsd
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.openhab.tools.analysis.utils.CachingHttpClient.getContent(CachingHttpClient.java:80)
        at org.openhab.tools.analysis.utils.CachingHttpClient.lambda$get$0(CachingHttpClient.java:70)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870)
        at org.openhab.tools.analysis.utils.CachingHttpClient.get(CachingHttpClient.java:70)
        ... 34 more
```

**Comment by kaikreuzer** [comment]
I cannot see this on our Jenkins.
Can you access this url through curl?

**Comment by hmerk** [comment]
Same happend to my new WeMo PR within Travis Build.

**Comment by kaikreuzer** [comment]
@ghys Any idea where this could come from? Could it be related to Cloudflare in some way?

**Comment by digitaldan** [comment]
According to this support article, cloudflare does not send 403 errors, so could the origin server (netify) be not happy with something in the request? Could the build server have a DNS issue and is trying to hit the origin server directly?  Just tossing ideas out :-) 

https://community.cloudflare.com/t/community-tip-fixing-error-403-forbidden/53308

**Comment by digitaldan** [comment]
Actually that support article says they will send back a 403 error if 

```
Cloudflare will serve 403 responses if the request violated either a default WAF rule enabled for all orange-clouded Cloudflare domains or a WAF rule enabled for that particular zone.

Cloudflare will also serve a 403 Forbidden response for SSL connections to subdomains that aren’t covered by any Cloudflare or uploaded SSL certificate.
```

**Comment by kaikreuzer** [comment]
Hm, we don't have any firewall rules set up.
The strange thing is that the url https://openhab.org/schemas/config-description-1.0.0.xsd works smoothly in the browser...
Maybe Cloudflare has an issue with Travis as there are too many malicious request originating from their servers?

**Comment by cweitkamp** [comment]
Just a minor notice:

https://openhab.org/schemas/binding-1.0.0.xsd seems to be redirected (301 permanent) to https://www.openhab.org/schemas/binding-1.0.0.xsd. Might that cause the 403 error?

![image](https://user-images.githubusercontent.com/5131747/69555432-7bd71300-0fa3-11ea-8523-2e97a1c775a1.png)

**Comment by kaikreuzer** [comment]
It should not, but it might be that the sun.net HTTP client has an issue with that.
The easy solution should thus be to change the code to use `www` as well, wdyt?

**Comment by ghys** [comment]
Another possible fix would be to set openhab.org as the primary domain on Netlify (and I suppose, redirect www.openhab.org to openhab.org, that is, the reverse of what we have now - not sure if it could lead to SEO issues?)

![image](https://user-images.githubusercontent.com/2004147/69557202-7cbd7400-0fa6-11ea-9aeb-a6e6371486b1.png)

Note that it's complaining because it detected the DNS doesn't point to their servers anymore - not an issue per se but worth mentioning.

**Comment by cweitkamp** [comment]
> The easy solution should thus be to change the code to use www as well, wdyt?

Should be possible. But we have to change it in all of our repositories.

**Comment by ghys** [comment]
I have reproduced the 403 error using a Scaleway I use for personal stuff.

I think Cloudflare blocks the request on a combination of origin IP address from Scaleway + user agent like `Java/1.8.123`, probably indeed due to prior abuse:
```
root@scw-xxxxxx:~# curl -v -A "Java/1.8.123" https://openhab.org/schemas
* About to connect() to openhab.org port 443 (#0)
*   Trying 104.24.114.50...
* connected
* Connected to openhab.org (104.24.114.50) port 443 (#0)
...
> GET /schemas HTTP/1.1
> User-Agent: Java/1.8.123
> Host: openhab.org
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 403 Forbidden
< Date: Mon, 25 Nov 2019 16:46:32 GMT
< Content-Type: text/plain; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d97fdfbf39fb27e7ea1c322b545003a561574700392; expires=Tue, 24-Nov-20 16:46:32 GMT; path=/; domain=.openhab.org; HttpOnly
< Cache-Control: max-age=10
< Expires: Mon, 25 Nov 2019 16:46:42 GMT
< Alt-Svc: h3-23=":443"; ma=86400
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 53b5196ead31ee6d-CDG
<
* Connection #0 to host openhab.org left intact
error code: 1010* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```
Error code 1010 is: _The owner of this website has banned your access based on your browser's signature_

From the same Scaleway, but using another User-Agent (`curl/7.xx.x`):
```
root@scw-xxxxxx:~# curl -v https://openhab.org/schemas
* About to connect() to openhab.org port 443 (#0)
*   Trying 104.24.114.50...
* connected
* Connected to openhab.org (104.24.114.50) port 443 (#0)
...
> GET /schemas HTTP/1.1
> User-Agent: curl/7.26.0
> Host: openhab.org
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 25 Nov 2019 16:50:44 GMT
< Content-Type: text/plain
< Content-Length: 47
< Connection: keep-alive
< Set-Cookie: __cfduid=df123e07aebe55c36c7522617abdea00b1574700644; expires=Wed, 25-Dec-19 16:50:44 GMT; path=/; domain=.openhab.org; HttpOnly
< Location: https://www.openhab.org/schemas
< Strict-Transport-Security: max-age=31536000
< Age: 6
< Cache-Control: public,s-max-age=604800
< X-NF-Request-ID: 6e090c98-7c32-456d-a952-60b659e54b57-1467677
< CF-Cache-Status: DYNAMIC
< Alt-Svc: h3-23=":443"; ma=86400
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 53b51f949ee1ee89-CDG
<
Redirecting to https://www.openhab.org/schemas
* Connection #0 to host openhab.org left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

**Comment by ghys** [comment]
@kaikreuzer according to https://support.cloudflare.com/hc/en-us/articles/360029779472#error1010 disabling the "Browser Integrity Check" feature may also work.

**Comment by kaikreuzer** [comment]
Great, thanks for the analysis!

>  The owner of this website has banned your access based on your browser's signature

Java is BAAAAAD 🤔 

> disabling the "Browser Integrity Check" feature may also work.

Sounds like the best option to me - I have disabled it now.
Could you rerun your test?

**Comment by kaikreuzer** [comment]
@lolodomo & @hmerk I would hope that it is solved. If so, please close the issue :-)

**Comment by hmerk** [comment]
Seems to be solved, not seeing it on WeMo PR anymore. Now it‘s just the itest issue....

**Comment by lolodomo** [comment]
The issue is fixed for me too.

**Comment by marcelrv** [comment]
I still see this error. Do I need to do something on my end to get it fixed or does the issue need to be reopened?


```
[ERROR] Unable to get XSD file https://openhab.org/schemas/config-description-1.0.0.xsd : Unable to get https://openhab.org/schemas/config-description-1.0.0.xsd                                                                             java.io.IOException: Unable to get https://openhab.org/schemas/config-description-1.0.0.xsd                                                                                                                                                      at org.openhab.tools.analysis.utils.CachingHttpClient.get (CachingHttpClient.java:72)                                                                                                                                                        at org.openhab.tools.analysis.checkstyle.OhInfXmlValidationCheck.getXSD (OhInfXmlValidationCheck.java:232)                                                                                                                                   at org.openhab.tools.analysis.checkstyle.OhInfXmlValidationCheck.beginProcessing (OhInfXmlValidationCheck.java:125)                                                                                                                          at com.puppycrawl.tools.checkstyle.Checker.process (Checker.java:210)                                                                                                                                                                        at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:202)                                                                                                                 at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.executeReport (AbstractCheckstyleReport.java:533)                                                                                                                            at org.apache.maven.plugins.checkstyle.CheckstyleReport.executeReport (CheckstyleReport.java:57)                                                                                                                                             at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)                                                                                                                                                    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenReport.java:143)                                                                                                                                                     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                                                                                                                        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)                                                                                                                                                            at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck (AbstractChecker.java:114)                                                                                                                                                  at org.openhab.tools.analysis.tools.CheckstyleChecker.execute (CheckstyleChecker.java:130)                                                                                                                                                   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                                                                                                                        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)                                                                                                                                                          at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)                                                                                                                                                          at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)                                                                                                                                                          at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                                                                                                                                 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                                                                                                                                  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)                                                                                                                    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                                                                                                                                  at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                                                                                                                                                                           at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                                                                                                                                                                           at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                                                                                                                                                                             at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                                                                                                                                                                                 at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                                                                                                                                                                                  at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                                                                                                                                                                    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                                                     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                                                   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                                                           at java.lang.reflect.Method.invoke (Method.java:566)                                                                                                                                                                                         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                                                                                                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)                                                                                                                                                              at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                                                                                                                                    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)                                                                                                                                                            Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure                                                                                                                                                          at sun.security.ssl.Alert.createSSLException (Alert.java:128)                                                                                                                                                                                at sun.security.ssl.Alert.createSSLException (Alert.java:117)                                                                                                                                                                                at sun.security.ssl.TransportContext.fatal (TransportContext.java:308)                                                                                                                                                                       at sun.security.ssl.Alert$AlertConsumer.consume (Alert.java:279)                                                                                                                                                                             at sun.security.ssl.TransportContext.dispatch (TransportContext.java:181)                                                                                                                                                                    at sun.security.ssl.SSLTransport.decode (SSLTransport.java:164)                                                                                                                                                                              at sun.security.ssl.SSLSocketImpl.decode (SSLSocketImpl.java:1152)                                                                                                                                                                           at sun.security.ssl.SSLSocketImpl.readHandshakeRecord (SSLSocketImpl.java:1063)                                                                                                                                                              at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:402)                                                                                                                                                                    at sun.net.www.protocol.https.HttpsClient.afterConnect (HttpsClient.java:567)                                                                                                                                                                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect (AbstractDelegateHttpsURLConnection.java:185)                                                                                                                       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1581)                                                                                                                                                 at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1509)                                                                                                                                                  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:245)                                                                                                                                        at org.openhab.tools.analysis.utils.CachingHttpClient.getContent (CachingHttpClient.java:79)                                                                                                                                                 at org.openhab.tools.analysis.utils.CachingHttpClient.lambda$0 (CachingHttpClient.java:69)                                                                                                                                                   at com.google.common.cache.LocalCache$LocalManualCache$1.load (LocalCache.java:4876)                                                                                                                                                         at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture (LocalCache.java:3529)                                                                                                                                                at com.google.common.cache.LocalCache$Segment.loadSync (LocalCache.java:2278)                                                                                                                                                                at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad (LocalCache.java:2155)                                                                                                                                                         at com.google.common.cache.LocalCache$Segment.get (LocalCache.java:2045)                                                                                                                                                                     at com.google.common.cache.LocalCache.get (LocalCache.java:3951)                                                                                                                                                                             at com.google.common.cache.LocalCache$LocalManualCache.get (LocalCache.java:4871)                                                                                                                                                            at org.openhab.tools.analysis.utils.CachingHttpClient.get (CachingHttpClient.java:69)                                                                                                                                                        at org.openhab.tools.analysis.checkstyle.OhInfXmlValidationCheck.getXSD (OhInfXmlValidationCheck.java:232)                                                                                                                                   at org.openhab.tools.analysis.checkstyle.OhInfXmlValidationCheck.beginProcessing (OhInfXmlValidationCheck.java:125)                                                                                                                          at com.puppycrawl.tools.checkstyle.Checker.process (Checker.java:210)                                                                                                                                                                        at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle (DefaultCheckstyleExecutor.java:202)                                                                                                                 at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.executeReport (AbstractCheckstyleReport.java:533)                                                                                                                            at org.apache.maven.plugins.checkstyle.CheckstyleReport.executeReport (CheckstyleReport.java:57)                                                                                                                                             at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)                                                                                                                                                    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenReport.java:143)                                                                                                                                                     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                                                                                                                        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)                                                                                                                                                            at org.openhab.tools.analysis.tools.AbstractChecker.executeCheck (AbstractChecker.java:114)                                                                                                                                                  at org.openhab.tools.analysis.tools.CheckstyleChecker.execute (CheckstyleChecker.java:130)                                                                                                                                                   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)                                                                                                                                        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)                                                                                                                                                          at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)                                                                                                                                                          at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)                                                                                                                                                          at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)                                                                                                                                 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)                                                                                                                                  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)                                                                                                                    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)                                                                                                                                                  at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)                                                                                                                                                                           at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)                                                                                                                                                                           at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)                                                                                                                                                                             at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)                                                                                                                                                                                 at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)                                                                                                                                                                                  at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)                                                                                                                                                                                    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)                                                                                                                                                                     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)                                                                                                                                                   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)                                                                                                                                           at java.lang.reflect.Method.invoke (Method.java:566)                                                                                                                                                                                         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)                                                                                                                                                      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)                                                                                                                                                              at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)                                                                                                                                                    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)                                                                                                                                                            [ERROR] Could not read src/main/feature/feature.xml                                                                                                                                                                                          [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.                                                                                                                                                                 [WARNING] XML validation will be skipped as the schema file download failed.            
```
