### ISSUE TITLE
Change behavior when .persist file is reloaded or when starting OH if no .persist file is loaded yet.

### ISSUE THREAD

**Issue by miwok72** [openhab/openhab-core#3590]
See this thread: [OH community](https://community.openhab.org/t/items-are-stored-in-influxdb-but-are-not-present-in-any-persist-file-are-also-not-persisted-via-rule/146219)
github issue: [github](https://github.com/openhab/openhab-addons/issues/14889)

and especially here: [https://community.openhab.org/t/items-are-stored-in-influxdb-but-are-not-present-in-any-persist-file-are-also-not-persisted-via-rule/146219/19](https://community.openhab.org/t/items-are-stored-in-influxdb-but-are-not-present-in-any-persist-file-are-also-not-persisted-via-rule/146219/19)

... If no .persist file is present, the default strategy is used and that is “everyChange”. So I would guess that when the file is unloaded, the default strategy is applied and until the file is parsed that is active. So there is a short time between unloading the old model and loading the new model with the default strategy in place. That would explain why only very few values are persisted. ...

**Comment by lolodomo** [comment]
@J-N-K : is this issue (and mine) really fixed now? How was it fixed? I don't see an obvious link with the merged PR.

**Comment by J-N-K** [comment]
The difference is that now the model is not removed and added when it is modified, but updated in the `PersistenceManager`. This prevents applying the default strategy on changes. 

The only issue still left is that there might be a small chance that the service is activated before any model is parsed (this is your issue). However, this is a design decision to use "persist all" as default strategy.
